//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceSIMReduxWorkingDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpaceSIMReduxWorkingDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Goku {
            get {
                object obj = ResourceManager.GetObject("Goku", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Luffy {
            get {
                object obj = ResourceManager.GetObject("Luffy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to They were the original species on the planet until the mutations gave way to many different variants and so many hero&apos;s.  For now though you land in close on a moon light night and you wonder if you alone then you see eyes in the night and a sound like a blade being drawn....&quot;Best be moving along bub...&quot;.
        /// </summary>
        internal static string ReadMeEarth {
            get {
                return ResourceManager.GetString("ReadMeEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You go to land but there is none, it is early morning and you hover low over the water then you see him man on the bow of a ship stretching in the fog.
        ///Before he could have possible nocied you he looks suddenly his eyes flashing red with a look upon his face so severe it shakes you..you get the feeling that
        ///if you leave his ship alone he will leave yours alone..
        /// </summary>
        internal static string ReadMeOnePiece {
            get {
                return ResourceManager.GetString("ReadMeOnePiece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Kindom of the heart is what it is known as and light holds this particular solar system together, althought it is dark when you land and a dark figure
        ///stares at you through the night and there is a forboding that feels like the dark saying &quot;leave now or forever become heartless&quot;.  
        ///
        ///-Notes from the computer of a traveler who has landed on the planet-
        ///The planet is a very dark place and the only light that can be seen is the light of the stars and the moon, which is always full.  The planet is also h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadMeTheKindom {
            get {
                return ResourceManager.GetString("ReadMeTheKindom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The planet Yardrat, while the species shown here is not the only one it will certainly be the first one you run into if you have a bone to pick 
        ///with the planet, at least for now.  He is a a sayian and is currently recupurating and is training with the Native species the Yardrat, from which the planet draws thes name from.
        ///They are a peaceful species that have mastered the art of teleportation and are known for their unique fighting style called 
        ///&quot;Yardrat Style&quot;.  Despite their peaceful nature, they can  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReadMeYardrat {
            get {
                return ResourceManager.GetString("ReadMeYardrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sora____ {
            get {
                object obj = ResourceManager.GetObject("Sora...?", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap space_background {
            get {
                object obj = ResourceManager.GetObject("space_background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sunset_on_Mars {
            get {
                object obj = ResourceManager.GetObject("Sunset on Mars", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Wolverine {
            get {
                object obj = ResourceManager.GetObject("Wolverine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
